sudo: false
dist: trusty

addons:
  chrome: stable

language: node_js

node_js:
  - '12'
  - '13'

branches:
  only:
    - master
    - beta
    - release
    - auto
    - '/^greenkeeper.*$/'

cache:
  yarn: true
  directories:
    - '$HOME/.npm'
    - '$HOME/.cache'

matrix:
  fast_finish: true

env:
  secure: 'NPnPer/Wtmdsyv70GGPYEmkDXIWftHAxPPYwRteMwcb74CgEqB200NSv6u8eENxmnXnHko3k9SmhYQkXi2Oz/bKu7xpRNqlDPOMvXWGJl9UIN56pnrKZ11iO3kPmW/OuQsDT3tjn/obQ/qfpW7foxqqq2krHuWwURaFjUvpQWsRS7BVreyXljrij5AnmFVYhqGaSq8drOBQ8Mu/MFZ6q/eu4DSRzQG+H4Awf2VPciZzF7ilMFedAVvzu5nd0pkEL17kEi4rgPIIexvim0wzaCoIABALnSzmZGIXANDKybVd15pdtQ4QwgrS5N3tsHP8BZ4zQhuAzMrVg9ATZTRW1p7RCfjP5g+sp9b1pGPoyVWQwtXNgQxYABr+stWNXmf6/VjhsmS5dMKyX1NLViV0ek71g6V2OXjyX8KSuCxHjxs76VifEVEB+wRAE/JO8+da3jNrmPS0PqxONPaxYw+OtEbJILghERQVdgCjxOJ1Hj3dBSKP49IFNCIc7kmWH5CAjKZcZSkID74Uz5d1JTqiaytU/Tf40/OtU500Mcv+Dk8s3D6x6aXpaU2YzXQ3RTl4+b512vOaeWbDEE0E1zqgSmtDZSMmH1ZnLd3pYE8GiyP4mibDrOEjICt01DI+4w9+sv3kwnR3PlQth111Y8GDkPAl4X1BeNH8i0hOKRGthK5A=' # TEST_TOKEN

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - echo "${TEST_TOKEN}"
  # - curl -s "https://${SAMPLE_TOKEN}:@packagecloud.io/install/repositories/movableink/studio/script.node.sh" | force_npm=1 bash

script:
  - yarn run test
  - yarn run test:beta
