sudo: false
dist: trusty

addons:
  chrome: stable

language: node_js
node_js:
  - "8"
  - "9"

branches:
  only:
    - master
    - beta
    - release
    - auto
    - /^greenkeeper.*$/

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bower's cache

env:
  - TEST_COMMAND=test-all

matrix:
  fast_finish: true

before_install:
  # travis currently includes yarn v0.17.8 (20170705)
  # this isn't new enough for our use of --non-interactive
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn run $TEST_COMMAND
