sudo: false
dist: trusty

addons:
  chrome: stable

language: node_js

node_js:
  - '12'
  - '13'

branches:
  only:
    - master
    - beta
    - release
    - auto
    - '/^greenkeeper.*$/'

cache:
  yarn: true
  directories:
    - '$HOME/.npm'
    - '$HOME/.cache'

matrix:
  fast_finish: true

env:
  global:
    secure: 'N5hTxDJ/cs91cpq0VLBV08DNSS0jSeQl197X8vhMCeh7KZdxChY/HsuY48Ko5KT4f0dfeiA9vC/W4ANEzQk2zZTVOy14EJwOg+MkR8vzPX4TYNywvzYQqPQ/ece/cd6VLhD3LPOM0Ch7gEAcs6p36/3TIwNUG22EuO/e3p8nbgS0vr4jQztQD/e41Le2encNZoj54ssauXhDcDYVQXTfYjUNOgoukIni+2RbfTEd8xgZqO0KTriwG156sW4VH2ubviOqB3pp608mClxoxzp/t8CqQSZ+He3i6t5GfVXq+ypFcuRxZkS0mGpkilAl+GsgBkQg+U3/o2uv8V1zFagw3S7X0BTgLuYKeJnuBsq3lFqjA2xgSOFR6MeSers/Y3Z+dVYPw59uOuvtf87wOR0uGndL8VDANMQwnSwMxbB6ZUr7rsYkJ+5kVOYrUaKMxysU2fXbU0XmuPg/M6H9SYm/xHsCPMbDTjuH8VBDHn/xS/P8ajjmSGwosEzQesXXnXLneKl+rE1xwsEK/DGQW3cv9XKbjuHH0QP8h6NglJPJKRjR/pd6UONVRF96/xh/QG6qV0BrccQFjd+F21IgR9zboEdPgEYoSUKBXuRrok+RuUAApmkuY72AEq116ZgXm0KjB6V4CK1v3TGTHMoa8Z6P5sOz+5qj5AQ+S6nYVpbHoPw=' #PACKAGE_CLOUD_TOKEN

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - curl -s "https://${PACKAGE_CLOUD_TOKEN}:@packagecloud.io/install/repositories/movableink/studio/script.node.sh" | force_npm=1 bash

script:
  - yarn run test
  - yarn run test:beta
