sudo: false
dist: trusty

addons:
  chrome: stable

language: node_js

node_js:
  - '12'
  - '13'

branches:
  only:
    - master
    - beta
    - release
    - auto
    - '/^greenkeeper.*$/'

cache:
  yarn: true
  directories:
    - '$HOME/.npm'
    - '$HOME/.cache'

matrix:
  fast_finish: true

env:
  secure: 'aqpUTlZMuBgVXNUCQtuiAsy0tQVAKZOiExiFnug33IfEguIhdw5WNLxcydYjpMX25MvlKIYuGYcnXbyLuTFJ/ZKue/2LrcyCu7SMkX39ugRyc6uXXGIVvgklrDCNTXiMMab90cREAvVdWQgPKw/4VIKsSPpi9E+chCW7FzwiMHzF6ZiFSx1ZK5/XbyjwPsP25hPwLruUUV2L6k7T/BrNSCPhBA2nBbEB2VItxwmRkGEnh3zeErAxzBWnNn5MyudBA0PIIgbW44J+jyJ2G929Gx2fr2k9YQURRBeBNtwLFo1gF9rAj98fJ9XCqPAJv5YNWYdIL47ctLkBo6/WrlyRN6jg+T7x2ExL11pUDud22xdSd6BrYcvmYapiaqFXzsV2mqO7eSWul17QreQ0WJt3t4mhMZ5hcTYylMZxtnJFqrw86Lv53LN2E1tt0BWwP2QIHt0L5Pmvdk5nBKY7c3Wz/CoVxpDMV99Jsr9wqUAW4Hca1jJ3t21dprzmeey+y/X514Egb1LwkOjt+kgZIDbrSMdjUhwravibZKCKCsZ3qD9HY1/4+Hy9v4JOP7ZRgptOjXrc1uGuiAmsyPRHTgWIU9ktWah7VNy9OZkOctKXJWNKv/mhMH6m6cuwvG9N9LT5NeIt1Et8RamLomES7HSIbq+UDD4r/S1imE87lCLng7U=' # PACKAGE_CLOUD_TOKEN

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - curl -s "https://${PACKAGE_CLOUD_TOKEN}:@packagecloud.io/install/repositories/movableink/studio/script.node.sh" | force_npm=1 bash

script:
  - yarn run test
  - yarn run test:beta
