import index from './index.html';

const common = {
  startComment:
    '<!-- MI WYSIWYG: DO NOT MODIFY CODE BEYOND THIS POINT. This code is auto-generated by Studio and will be overwritten -->',
  finishComment: '<!-- END MI WYSIWYG -->',
  startCommentReg: '<!-- MI WYSIWYG: DO NOT MODIFY.*?-->'
};
common.regex = new RegExp(`(${common.startCommentReg}|${common.finishComment})`, 'm');

export function wysiwygContent() {
  const parts = index.split(common.regex);
  if (parts.length !== 5) {
    throw 'missing wysiwyg block from html';
  }

  return parts[2];
}
